import AddToDeck from './AddToDeck.png'
import Card_2 from './Card_2.png'
import Card from './Card.png'
import Decks from './Decks.png'
import EditCards from './EditCards.png'
import EditDeck from './EditDeck.png'
import GoogleMeaning from './GoogleMeaning.png'
import Lyrics from './Lyrics.png'
import LyricsMenu from './LyricsMenu.png'
import LyricsMenuCropped from './LyricsMenuCropped.png'
import Search from './Search.png'
import Logo from './Logo.png'
import Appstore from './Appstore.svg'

export {AddToDeck, Card, Card_2, Decks, EditCards, EditDeck, GoogleMeaning, Lyrics, LyricsMenu, Search, Logo, Appstore, LyricsMenuCropped}